linters:
  disable-all: true
  enable:
    # defaults
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # bugs
    - gosec
    - bodyclose
    # performance
    - noctx
    - perfsprint
    - prealloc
  fast: true
