FROM golang:1.17-bullseye as build

ARG BUILD_OS
ARG BUILD_ARCH

RUN go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /src
COPY . .
RUN GOOS=${BUILD_OS} GOARCH=${BUILD_ARCH} CGO_ENABLED=1 go build -gcflags "all=-N -l" -o ./neon cmd/exec/*.go

ENTRYPOINT ["/go/bin/dlv"]
