[app.store.storage]

[app.fetcher.providers.api.rest]
timeout = 15
retry = 3
delay = 5

[app.fetcher.providers.api.rest.headers]
Content-Type = "application/json"
Authorization = "Bearer: <secret_token>"

[app.loader]
execStartup = 15
execInterval = 300
execFailsafeInterval = 60
execMaxOps = 100
execMaxDelay = 60

[app.loader.rules.load-config.raw.resource.config.api]
method = "GET"
url = "https://<backend_url>/static/config.json"

[app.loader.rules.load-pages.json]
filter = "$.data"

[app.loader.rules.load-pages.json.resource.pages.api]
method = "GET"
url = "https://<backend_url>/api/v1/pages"
next = true
nextParser = "body"
nextFilter = "$.links.next"

[app.loader.rules.load-pages.json.resource.pages.api.params]
type = "page"
language = "fr"
limit = "100"
sort = "-date"
include = "author"

[app.loader.rules.load-pages.json.itemParams]
slug = "$.attributes.slug"

[app.loader.rules.load-pages.json.itemResource."page-$id".api]
method = "GET"
url = "https://<backend_url>/api/v1/pages"

[app.loader.rules.load-pages.json.itemResource."page-$id".api.params]
slug = "$slug"

[app.server.listeners.secured.tls]
listenAddr = "0.0.0.0"
listenPort = 443
certFiles = ["cert.pem"]
keyFiles = ["key.pem"]

[app.server.listeners.unsecured.redirect]
listenAddr = "0.0.0.0"
listenPort = 80

[app.server.sites.main]
listeners = ["default", "secured"]

[app.server.sites.main.routes.default.middlewares]
[server.sites.main.routes.default.middlewares.logger]
file = "access.log"

[app.server.sites.main.routes.default.middlewares.static]
path = "app/static"

[app.server.sites.main.routes.default.handler.js]
index = "app/index.html"
bundle = "app/bundle.js"
cache = true
cacheTTL = 60

[[app.server.sites.main.routes.default.handler.js.rules]]
path = "^/"

[[app.server.sites.main.routes.default.handler.js.rules.state]]
key = "config"
resource = "config"

[[app.server.sites.main.routes.default.handler.js.rules]]
path = "^/(?P<slug>[^\\/]+)/?$"
last = true

[[app.server.sites.main.routes.default.handler.js.rules.state]]
key = "pages"
resource = "page-$slug"
export = true

[app.server.sites.main.routes."/robots.txt".handler.robots]
cache = true
cacheTTL = 60
sitemaps = ["https://<frontend_url>/sitemap.xml"]

[app.server.sites.main.routes."/sitemap.xml".handler.sitemap]
root = "https://<frontend_url>"
cache = true
cache_ttl = 60
kind = "sitemap"

[[app.server.sites.main.routes."/sitemap.xml".handler.sitemap.sitemap]]
name = "home"
type = "static"

[app.server.sites.main.routes."/sitemap.xml".handler.sitemap.sitemap.static]
loc = "/"
changefreq = "always"
priority = 1

[[app.server.sites.main.routes."/sitemap.xml".handler.sitemap.sitemap]]
name = "pages"
type = "list"

[app.server.sites.main.routes."/sitemap.xml".handler.sitemap.sitemap.list]
resource = "pages"
filter = "$.data"
itemLoc = "$.attributes.slug"
itemLastmod = "$.attributes.date"
changeFreq = "daily"
priority = 0.5
